server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:postgresql://database-1.cn2bloewwptn.us-west-1.rds.amazonaws.com:5432/postgres
    username: mhartley
    password: Meh030688
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        globally_quoted_indetifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false